### ISSUE TITLE
Add health of API without autenfication

### ISSUE THREAD

**Issue by Tezno** [sogilis/Voogle#175]
ex: /api/v1/health/live

**Comment by rodolphechartier** [comment]
Could it be possible to use another route than the prefixed one `/api/v1` ? All route beginning by this prefix needs an authentication.

(ex: `/health/v1` or `/health/api/v1`)

If not, I may have to re-write a lot of code.

**Comment by Isilud** [comment]
Yes it is, `/api/v1` is on a subrouter needing authentication. But you can use other prefix if you need.
