### ISSUE TITLE
MariaDB database does not update automatically

### ISSUE THREAD

**Issue by Isilud** [sogilis/Voogle#252]
When "video" table already exist, the database is not updated with the "video_status" column.
Stopping/starting  docker doesn't fix the issue, we had to delete manually the "mariadb" folder in "Voogle/docker/.data/mariadb".

**Comment by vlamy** [comment]
Can give a bit more detail please ? What request ? How can we reproduce ?

**Comment by vlamy** [comment]
🤔 Actually from your description it sounds like a legit behavior.

**Comment by Tezno** [comment]
The data of the database is stored in `docker/.data/mariadb/`. If the database changes (add/remove column) the schema file of the database is not played -> CREATE TABLE IF NOT EXISTS videos.
We can have inconsistencies, it is necessary to delete the data (directory mariadb) or have an upgrade policy
