### ISSUE TITLE
Convert cover image to compressed format (jpg)

### ISSUE THREAD

**Issue by ClerySem** [sogilis/Voogle#435]
We should compress cover image to limit home page load time.
It could be a task for the encoder

**Comment by rodolphechartier** [comment]
I am looking for a solution to this issue and I found this : https://github.com/yusukebe/go-pngquant.

I'm still looking for other solutions, and we may compare them afterwards ?

**Comment by rodolphechartier** [comment]
And an other one : https://dev.to/franciscomendes10866/image-compression-with-golang-k2p

It uses bimg, it says it's easy to use but i don't know how good the quality of the compression.

**Comment by rodolphechartier** [comment]
And this one is from a single guy, not too many stars / fork on his repo. Is it worth ? https://github.com/foobaz/lossypng/
